export { default as Intro } from './Intro';
export { default as Home } from './Home';
export { default as NewGame } from './NewGame';
export { default as JoinGame } from './JoinGame';
export { default as Players } from './Players';
export { default as Game } from './Game';
export { default as About } from './About';
export { default as Leaderboard } from './Leaderboard';
export { default as GameOver } from './GameOver';